server:
   port: 9080
   error:
      path: /error
      whitelabel:
         enabled: true

spring:
   datasource:
      name: ecommercedb

   jpa:
      show-sql: false

   h2:
      console:
         enabled: true
         path: /h2-console